services:
  postgres:
    image: postgres:16
    container_name: dvd_collection_db
    environment:
      POSTGRES_USER: dvduser
      POSTGRES_PASSWORD: dvdpass
      POSTGRES_DB: dvd_collection
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
